name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npx yarn install

      - name: Build
        run: npm run build

      - name: Upload production-build
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-build
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          publish_dir: ./dist
